version: "3"
services:
  eth:
    image: ethereum/client-go:stable
    volumes: 
      - eth-data:/data
    ports:
      - 30303:30303/tcp
      - 30304:30304/udp
      - 6060:6060
    command:
      - --goerli
      - --rpc
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr=0.0.0.0
      - --datadir=/data
    networks:
      - core

volumes:
  eth-data:

networks:
  core:
    external: true
