version: "3"
services:

  beacon-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    restart: always
    network_mode: "host"
    volumes:
      - beacon-data:/data
    ports:
      - "4000:4000"
      - "13000:13000"
    command: --datadir=/data

  validator:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    restart: always
    network_mode: "host"
    depends_on:
      - beacon-node
    volumes:
      - validator-data:/data
    command: --beacon-rpc-provider=127.0.0.1:4000 \
             --keymanager=keystore \
             --keymanageropts=/data/keystore.json

volumes:
  beacon-data:
  validator-data:
