version: "3"
services:

  beacon-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    restart: always
    volumes:
      - prysm-data:/data
    ports:
      - "4000:4000"
      - "13000:13000"
    command: --datadir=/data

  validator:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    restart: always
    depends_on:
      - beacon-node
    volumes:
      - /home/owodunni/.prysm/validator:/data
    command: --beacon-rpc-provider=127.0.0.1:4000 \
             --keystore-path=/data \
             --password=$VALIDATOR_PASSWORD
volumes:
  prysm-data: