apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: slasher
  name: slasher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slasher
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: slasher
    spec:
      containers:
      - args:
        - --beacon-rpc-provider=beacon-node:4000
        - ' --datadir=/data'
        image: gcr.io/prysmaticlabs/prysm/slasher:latest
        imagePullPolicy: ""
        name: slasher
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: slasher-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: slasher-data
        persistentVolumeClaim:
          claimName: slasher-data
status: {}
